# permissions to do edit hostmigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostmigration-editor-role
rules:
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - hostmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - hostmigrations/status
  verbs:
  - get
  - patch
  - update
