# permissions to do viewer hostmigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostmigration-viewer-role
rules:
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - hostmigrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - hostmigrations/status
  verbs:
  - get
