# permissions to do edit ingressmigrates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressmigrate-editor-role
rules:
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - ingressmigrates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - ingressmigrates/status
  verbs:
  - get
  - patch
  - update
