# permissions to do viewer ingressmigrates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressmigrate-viewer-role
rules:
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - ingressmigrates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - ingressmigrates/status
  verbs:
  - get
