# permissions to do viewer routemigrates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routemigrate-viewer-role
rules:
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - routemigrates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - routemigrates/status
  verbs:
  - get
