# permissions to do edit routemigrates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routemigrate-editor-role
rules:
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - routemigrates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dioscuri.amazee.io
  resources:
  - routemigrates/status
  verbs:
  - get
  - patch
  - update
