apiVersion: v1
entries:
  dioscuri:
  - apiVersion: v2
    appVersion: 0.1.6rc2
    created: "2020-10-19T17:43:23.822701+11:00"
    description: A Helm chart for dioscuri
    digest: 26dabd76ba6be80d2d2bb96be56a9072c9898171bea55db946b6f55156a83ea2
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.6rc1
    created: "2020-10-19T17:43:23.822222+11:00"
    description: A Helm chart for dioscuri
    digest: 061da4faee494f78731af48db46d3af8c1e388c0c292b91f5ebb00e3c4c16e84
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-19T17:43:23.821449+11:00"
