apiVersion: v1
entries:
  dioscuri:
  - apiVersion: v2
    appVersion: 0.1.8
    created: "2020-12-21T09:45:35.431278+11:00"
    description: A Helm chart for dioscuri
    digest: 37235ce0c772eeab232b109950fd7c5e180a076faa30e2a0f0c5449d94233518
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2020-12-21T09:45:35.430855+11:00"
    description: A Helm chart for dioscuri
    digest: 282b5b1255ab4a70e7fd8b0e592711db50b14c35fdfca931a3c587aaa1b1cf2d
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2020-12-21T09:45:35.430349+11:00"
    description: A Helm chart for dioscuri
    digest: ad08ced993bb6926a6c26cf78262c09d1926a6c3b8444e1b0af46e5fbe5e33ae
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.6rc2
    created: "2020-12-21T09:45:35.429876+11:00"
    description: A Helm chart for dioscuri
    digest: a135357d009a3e4070bedaf72d7b5c96cc71d8d21f54f54094efc237371bfac0
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.6rc2
    created: "2020-12-21T09:45:35.429363+11:00"
    description: A Helm chart for dioscuri
    digest: 057df5c8fcc93af6f11a6ff897380993afa7d19ecc4a22de693903759dab44b5
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.6rc2
    created: "2020-12-21T09:45:35.428017+11:00"
    description: A Helm chart for dioscuri
    digest: 26dabd76ba6be80d2d2bb96be56a9072c9898171bea55db946b6f55156a83ea2
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.6rc1
    created: "2020-12-21T09:45:35.427167+11:00"
    description: A Helm chart for dioscuri
    digest: 061da4faee494f78731af48db46d3af8c1e388c0c292b91f5ebb00e3c4c16e84
    name: dioscuri
    type: application
    urls:
    - dioscuri-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-21T09:45:35.423967+11:00"
