---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dioscuri.fullname" . }}
  labels:
    {{- include "dioscuri.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "dioscuri.selectorLabels" . | nindent 4 }}
