apiVersion: v1
kind: Namespace
metadata:
  name: test-ns1
---
apiVersion: v1
kind: Service
metadata:
  name: example-nginx-svc
  namespace: test-ns1
  labels:
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: example-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  namespace: test-ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-nginx
  template:
    metadata:
      labels:
        app: example-nginx
    spec:
      containers:
      - name: example-nginx
        image: amazeeio/nginx-test:ns1
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test1.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test2.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test3.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test3.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test4.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test4.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test5.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test5.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test6.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test6.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test7.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test7.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test8.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test8.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test9.localhost
  namespace: test-ns1
  labels:
    dioscuri.amazee.io/migrate: 'true'
spec:
  rules:
  - host: test9.localhost
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: example-nginx-svc
            port:
              number: 80